config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: "top#index"
  devise_for :users, controllers: {
      :omniauth_callbacks => "users/omniauth_callbacks",
  }

  resources :users, except: [:index]

  resources :works

  get 'myworks/index', to: 'myworks#index'
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
    mount_uploader :video, VideoUploader
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
     @works = Work.order(created_at: :desc)
     @title = 'ワークス一覧'
  end


    def show
     @work = Work.find(params[:id])
    end

    def new
     @work = Work.new
     @title = '新規ワークの作成'
    end

    def create
     @work = current_user.works.build(works_params)
     if @work.save
       flash[:success] = "新規Workを作成しました！"
       redirect_to @work
     else
       render 'new'
     end
    end

    def edit
     @work = Work.find(params[:id])
    end

  def update
    respond_to do |format|
      if @work.update(edit_work_params) && @work.video.recreate_versions!
        format.html { redirect_to @work, notice: 'ワーク内容が更新されました。' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end



    def destroy
     @work = current_user.works.find_by(id: params[:id])
     return redirect_to root_url if @work.nil?
     @work.destroy
     flash[:success] = 'ワークは削除されました.'
     redirect_to works_path
    end



    def test
      return a=1
    end


  def works_params
    params.require(:work).permit(:title, :youtube_id, :thumbnail, :description, :youtube_url, :video)
  end

  def edit_work_params
    params.require(:work).permit(:title, :youtube_id, :thumbnail, :description, :youtube_url, :video)
  end

  def works_owner
    @work = Work.find(params[:id])
    unless @work.user_id == current_user.id
      flash[:notice] = 'Access denied as you are not owner of this work'
      redirect_to works_path
    end
  end
end

app/helpers/works_helper.rb
module WorksHelper
  def embed(youtube_url)
    if @work.youtube_url.present?
        youtube_id = youtube_url.split("=").last
        content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
    end
  end

  def imaged(youtube_url)
    youtube_id = youtube_url.split("=").last
    img_tag("//img.youtube.com/vi/#{youtube_id}/mqdefault.jpg")
  end

  def img_tag(path)
      if path.blank?
        logger.error('InvalidImagePath path is blank')
        path = 'images/no_image.png'
      end
      image_tag path
    rescue StandardError
      logger.error("InvalidImagePath : #{path}")
      image_tag 'images/no_image.png'
    end

end

app/views/works/_list.html.erb
<div class="container">
  <div class="container-inner inner-default clearfix">
    <% works.order("created_at desc").each do |work| %>
      <div class="item-box">
        <div class="image">
          <div class="img-wrap">

            <%= link_to image_tag(work.video_url(:screenshot).to_s, id: "video", :alt => "screenshot"), work %>

          </div>
        </div>
        <div class="detail">
          <p class="title">
            <%= work.title %>
            <!-- period date -->
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/works/edit.html.erb
<% content_for :head do %>
  <meta name="title" content="<%=@work.title %>の編集">
  <meta name="description" content="<%=@work.title %>の編集">
<% end %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3 edit-work">
  <h3 style="text-align: center;">Edit your own Work!!</h3>
    <%= simple_form_for(@work) do |f| %>
    <!-- error messages -->
    <%= f.error_notification %>

      <%= f.input :title, :input_html => { :class => 'form-control' } , label: 'Work Title' ,error: 'ワークは必須です。', :placeholder => "(ex) My second locking choreography" %><br/>

      <!-- <%= f.input :youtube_url, as: :url, label: 'Youtube動画 URL', :input_html => { :class => 'form-control' } , :placeholder => "https://www.youtube.com/watch?v=xxxxxxxxxxx" %></br> -->
      <%= f.label :video, "Video Work",  class: 'control-label' %>
      <%= f.file_field :video,  :accept => 'video/*' %><br/>
      <%= f.label :description, "Description",  class: 'control-label' %>
      <%= f.text_area :description, class: 'form-control' %><br/>
      <%= f.submit "更新する！", class: "btn btn-large btn-primary form-control" %>

    <% end %>
  </div>
</div>

app/views/works/index.html.erb
<% content_for :head do %>
  <meta name="title" content="<%= @title %>">
  <meta name="description" content="Works 一覧">
<% end %>

<div class="container index-work">
    <div class="container">
      <%= render 'works/list' , works: @works %>
    </div>
</div>

app/views/works/my_works.html.erb
<% content_for :head do %>
  <meta name="title" content="<%= @title %>">
  <meta name="description" content="Works 一覧">
<% end %>

<div class="container index-work">
    <div class="container">
      <%= render 'works/myWorksList' , works: @works %>
    </div>
</div>

app/views/works/new.html.erb
<% content_for :head do %>
  <meta name="title" content="新規ワーク作成">
  <meta name="description" content="新しいワークを作成しよう">
<% end %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3 edit-work">
  <h3 style="text-align: center;">Create your own Work!!</h3>
    <%= simple_form_for(@work) do |f| %>
    <!-- error messages -->
    <%= f.error_notification %>

      <%= f.input :title, :input_html => { :class => 'form-control' } , label: 'Work Title' ,error: 'ワークは必須です。', :placeholder => "(ex) My second locking choreography" %><br/>


      <%= f.label :video, "Video Work",  class: 'control-label' %>

      <%= f.file_field :video,  :accept => 'video/*' %><br/>
      <%= f.label :description, "Description",  class: 'control-label' %>
      <%= f.text_area :description, class: 'form-control' %><br/>
      <%= f.submit "新規投稿する！", class: "btn btn-large btn-primary form-control" %>

    <% end %>
  </div>
</div>

app/views/works/show.html.erb
<% content_for :head do %>
  <meta name="title" content="<%=@work.title %>">
  <meta name="description" content="「<%= @work.title %>」に関する情報です">
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">
      <div class="workbox">
        <h2><%= @work.title %></h2>

        <div class= "youtube-container">
          <%= link_to @work.video_url.to_s do %>
            <%= image_tag(@work.video_url(:screenshot).to_s, id: "video", :alt => "screenshot") %>
          <% end %>

        </div>
        <p><%= @work.description %></p>
        <div>
          <% if current_user == @work.user && current_user != nil %>
              <%= link_to "Work edit", edit_work_path(@work), class: "btn btn-large btn-default edit-btn" %>
          <% end %>
        </div>
      </div>
        <p class="work-p"><%= @work.description %></p>
    </div>
  </div>
 </div>
</div>