config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: "top#index"
  devise_for :users, controllers: {
      :omniauth_callbacks => "users/omniauth_callbacks",
  }

  resources :users, except: [:index]

  resources :works

  get 'myworks/index', to: 'myworks#index'
end

app/views/common/_footer.html.erb
<footer class="footer">
  <ul class="navbar-nav">
    <li><%= link_to "What is Thalia?", '#', class: "link"  %> | <%= link_to "利用規約", '#', class: "link"  %> | <%= link_to "プライバシーポリシー", '#', class: "link"  %> | <%= link_to "お問い合わせ", '#', class: "link" %></li><br/>
    <li>© <%= Date.today.year %> Thalia.com All right reserved.</li>
  </ul>
</footer>

app/views/common/_header.html.erb
  <div class="navbar navbar-default navbar-fixed-top header">
    <div class="container">
      <nav>
      <button type="button", class="navbar-toggle" data-toggle='collapse' data-target='.navbar-responsive-collapse'>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav pull-right">
                <li><%= link_to "What is Thalia？",  root_path  %></li>
                  <li>
                    <%= link_to "Works", works_path %>
                  </li>
                 <% if user_signed_in? %>
                   <li>
                    <%= link_to "My Page", user_path(current_user) %>
                    </li>
                    <li>
                      <%= link_to "My Works", myworks_index_path %>
                    </li>
                    <li>
                      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                    </li>
                <% else %>
                    <li>
                      <%= link_to "Sign Up", user_google_oauth2_omniauth_authorize_path, :class => 'post' %>
                    </li>

                <% end %>
            </ul>
        </div>
        </nav>
    </div>
  </div>